### ISSUE TITLE
Cannot access IOwinContext from CredentialValidationFunction

### ISSUE THREAD

**Issue by jamescrowley** [IdentityModel/Owin.BasicAuthentication#1]
I can't currently find a way to access IOwinContext in the context of the CredentialValidationFunction. 

This is needed if, for instance, you needed to make decisions as to how to validate the credentials based on hostname (in a multi-tenanted environment, say).

However, not sure on your preferred approach to this without making it a breaking change. Thoughts? I'd be happy to raise a pull request, but thought I'd check with you first.

**Comment by leastprivilege** [comment]
since this will be a new package - we can do that. sent the PR.
